apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name: fargate-cluster
  region: us-east-1
 
fargateProfiles:
  - name: fargate-default
    selectors: 
      - namespace: kube-system
      - namespace: default